# Generated by Django 5.0.7 on 2024-08-01 20:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviación')),
                ('dialing_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Telefónico')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuario')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='El correo está verificado')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de verificación')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de teléfono')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es Admin?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='Usuario')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='El correo está verificado')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de verificación')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Número de teléfono')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es Admin?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', verbose_name='País')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
