# Generated by Django 5.0.7 on 2024-08-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta')),
                ('extension', models.CharField(max_length=10, verbose_name='Extensión')),
                ('size', models.CharField(max_length=20, verbose_name='Tamaño')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'files',
            },
        ),
    ]
