# Generated by Django 5.0.7 on 2024-08-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='deleted_at',
        ),
    ]
