# Generated by Django 5.0.7 on 2024-09-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Código Iso'),
        ),
    ]
