# Generated by Django 5.0.7 on 2024-09-03 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_country_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Clave de Sesión')),
                ('token_key', models.CharField(max_length=40, verbose_name='Clave de Token')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información del dispositivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información de las Sesiones',
                'verbose_name_plural': 'Historias',
                'db_table': 'session_info',
                'unique_together': {('session_key', 'token_key')},
            },
        ),
    ]
