# Generated by Django 5.0.7 on 2024-10-08 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_story_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario'),
        ),
    ]
