# Generated by Django 5.0.7 on 2024-10-08 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_historicaluser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Este correo electrónico ya está en uso.'}, max_length=255, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Este nombre de usuario ya está en uso.'}, max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está en uso.'}, max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nombre de usuario ya está en uso.'}, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario'),
        ),
    ]
